"""
RSSHub 模块常量
"""

LEGACY_SOURCE_ID = "legacy_rsshub_source"
LEGACY_COMPOSITE_ID = "legacy_rsshub_composite"
LEGACY_PLACEHOLDER_IDS = {LEGACY_SOURCE_ID, LEGACY_COMPOSITE_ID}

RSSHUB_ERROR_MISSING_TARGET = "MISSING_TARGET"
RSSHUB_ERROR_FETCH_FAILED = "FETCH_FAILED"
RSSHUB_ERROR_PROCESSING = "PROCESSING_ERROR"

