# VabHub Plugins 版本配置文件

version: "1.0.0"

# 依赖关系配置
dependencies:
  - repo: "vabhub-core"
    version: ">=1.0.0"

# 变更日志配置
changelog:
  format: "keepachangelog"
  categories:
    - "Added"
    - "Changed"
    - "Fixed" 
    - "Removed"
    - "Security"

# 插件系统配置
plugins:
  # 插件入口点
  entry_points:
    namespace: "vabhub.plugins"
    
  # 插件发现机制
  discovery:
    auto_discover: true
    plugin_dirs:
      - "plugins/"
    
  # 插件配置
  configuration:
    format: "yaml"
    required_fields:
      - "name"
      - "version"
      - "description"

# 最后更新
last_updated: "2025-10-26"